version: '3.8'
services:
  app:
    image: online-market-app:latest
    container_name: online-market-app
    build:
      context: .
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/online_market
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=auca@2023
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_SHOW_SQL=true
      - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.PostgreSQLDialect
      - SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL=true
      - SPRING_MAIL_HOST=smtp.gmail.com
      - SPRING_MAIL_PORT=587
      - SPRING_MAIL_USERNAME=bayizeremarius119@gmail.com
      - SPRING_MAIL_PASSWORD=kcxb hlwp rqkj eehn
      - SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH=true
      - SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE=true
      - SPRINGDOC_SWAGGER_UI_PATH=/swagger-ui.html
      - SPRINGDOC_SWAGGER_UI_ENABLED=true
      - SPRINGDOC_API_DOCS_PATH=/v3/api-docs
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - online-market-network
    restart: unless-stopped

  db:
    image: postgres:15
    container_name: online-market-db
    environment:
      - POSTGRES_DB=online_market
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=auca@2023
    ports:
      - "5433:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - online-market-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

networks:
  online-market-network:
    driver: bridge

volumes:
  postgres-data: